export enum MongoCollection {
    USER = 'users',
    ROLE = 'roles',
    POST = 'posts',
    COMMENT = 'comments',
    REACTION = 'reactions',
    REPORT = 'reports',
    NOTIFICATION = 'notifications',
    CHAT = 'chats',
    MESSAGE = 'messages',
    USER_TOKEN = 'user_tokens',
    SUBSCRIBE_REQUEST = 'subscribe_requests',
    GROUP = 'groups',
    JOIN_REQUEST = 'join_requests',
    GROUP_POSTS = 'group_posts',
    TAGS = 'tags',
}
