version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: social-network
    ports:
      - 27018:27017
    volumes:
      - social_network_data:/home/hanh/Desktop/hanh/Slides/20222/social-network-backend
volumes:
  social_network_data:
    driver: local