export enum CronJobKey {
    HAPPY_BIRTHDAY = 'HAPPY_BIRTHDAY',
    ONLINE_ALERT = 'ONLINE_ALERT',
    REDUCE_POINT = 'REDUCE_POINT',
    SLEEP_REMINDER = 'SLEEP_REMINDER',
    DAILY_SCAN = 'DAILY_SCAN',
    SURVEY_SCAN = 'SURVEY_SCAN',
}
